[tool.poetry]
name = "laptrack"
version = "0.1.4"
description = "LapTrack"
authors = ["Yohsuke Fukai <ysk@yfukai.net>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/yfukai/laptrack"
repository = "https://github.com/yfukai/laptrack"
documentation = "https://laptrack.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: BSD License",
]

[tool.poetry.urls]
Changelog = "https://github.com/yfukai/laptrack/releases"

[tool.poetry.dependencies]
python = "^3.8.1,<3.11"
click = "^8.0.1"
numpy = "^1.21.1"
lap = "^0.4.0"
scipy = "^1.7.0"
networkx = "^2.6.1"
pandas = "^1.3.1"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = {extras = ["toml"], version = "^6.1"}
safety = "^1.10.3"
mypy = "^0.910"
typeguard = "^2.13.0"
xdoctest = {extras = ["colors"], version = "^0.15.10"}
sphinx = "^4.0.3"
sphinx-autobuild = "^2021.3.14"
darglint = "^1.8.1"
reorder-python-imports = "^2.5.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-click = "^3.0.1"
Pygments = "^2.9.0"
jupyter = "^1.0.0"
xmltodict = "^0.12.0"
pandas = "^1.3.1"
matplotlib = "^3.4.2"
pytest-datadir = "^1.3.1"
sphinxcontrib-napoleon = "^0.7"

[tool.poetry.scripts]
laptrack = "laptrack.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["laptrack"]

[tool.coverage.report]
show_missing = true
fail_under = 90

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
